name: learn-github-actions
on: [push]
jobs:
  run_npm_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm build

  run_npm_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm test

  eslint_check:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v2

      # Install your dependencies
      - run: npm ci

      # Run ESLint
      - uses: eslint/github-action@v0
