# We give a name to our workflow
name: GitHub Action Example

# We determine what triggers our worklow
# In this example it's every pull request or push to the branch's master
on:
  pull_request:
  push:
    branches: -master

jobs:
  # within the workflow a job is configured called test
  # code below runs the test
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    # actions/ lines are necessary for github to even run the workflows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install
        run: npm install # needed for the test to run
      - name: Test
        run: npm test # it will actually run the test
